# train, test, deploy
runner_type: deploy_runner
general:
    n_class: 17
    input_channel: 32
    batch_size: 64
    epoch: 20
    workspace: ./checkpoints

model:
    pipeline_name: hydranet
    backbone_name: resnet_50
    head_name: classify_head
    feature_dim: 512

data:
    mean: [-3.33, -1.72, -2.23, -1.67, -1.34, -1.31, -1.51, -1.27, -1.42, -1.24,
           -1.91, -1.45, -1.91, -2.36, -1.17, -2.56, -7.44, -8.21, -2.25, -4.69,
           -1.60, -2.91, -1.33, -2.14, -2.74, -1.56, -3.88, -2.99, -2.74, -13.54,
           -7.96, -5.93]
    std: [27.37, 14.81, 13.76, 31.81, 12.24, 13.28, 19.87, 9.24, 16.43, 10.95,
          22.96, 14.84, 49.10, 17.24, 12.45, 30.18, 163.28, 204.12, 11.86, 97.54,
          12.70, 12.94, 13.81, 14.97, 10.41, 13.12, 13.37, 16.84, 15.26, 22.44,
          232.18, 21.27]
    win_size: 1000
    step_size: 100
    low_freq: 5
    high_freq: 45
    sample_rate: 1000
    enable_filter: false

identity_map: {
        "ltr": 0,
        "wsm": 1,
        "yl": 2,
        "zqy": 3,
        "cjl": 4,
        "cyl": 5,
        "das": 6,
        "dl": 7,
        "gjc": 8,
        "gr": 9,
        "lmw": 10,
        "lpr": 11,
        "lsb": 12,
        "lsh": 13,
        "tm": 14,
        "wjq": 15,
        "zjq": 16
    }


optim.params:
  weight_decay: 1.e-5
evaluator:
    type: evaluator

train:
    type: base_trainer
    dataset_type: base_dataset
    dataset_path: ./data2/train.jsonl
    optimizer: Adam
    initial_lr: 1.0e-4
    lr_strategy: Cosine
    criterions: NLLLoss #CELoss

val:
    dataset_path: ./data2/val.jsonl

test:
    model_path: ./checkpoints/2024.04.27/11-0.7806.pt
    dataset_path: ./data2/val.jsonl

inference:
    dataset_path: ./data2/feature_file.jsonl
    model_path: ./checkpoints/2024-07-21_17-40/5-0.9038.onnx
    sample_size: 3
    feature_file: "./data2/feature_file.jsonl"
    valid_identity: ["ltr", "wsm", "yl", "zqy"]
    conf_thres: 0.9
    static_num: 30

deploy:
    model_path: checkpoints/2024-07-21_17-40/5-0.9038.pt



    
